import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/NavBar';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{margin: 0}}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
